# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: "2.7"
        cache: 'pip'
    - run: pip install pandas
    - name: Run pub export
      run: |
        python pub-year-list.py --csv 2021 > bib-2021.csv
        python to_excel.py bib-2021
    - name: update the repo
      run: |
        git config --local user.name "auto updater"
        git config --local user.email "updater@bla.com"
        git add .
        git commit -m "Auto update pubs"
    - name: Push changes 
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
